name: Go

on:
  push:
    paths:
      - "**.go"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "**.go"
      - ".github/workflows/go.yml"

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'chore')" # skip if commit message contains 'chore'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Test
        run: go test ./...
